In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('emails2.csv');
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [3]:
df.shape

(5728, 2)

In [4]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [7]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [8]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [9]:
missing = 'no mail'
df.spam = df.spam.fillna(missing)

In [10]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [11]:
x = df.text.values

In [12]:
y = df.spam.values

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x,y,test_size = 0.2)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv = CountVectorizer()

In [17]:
X_train = cv.fit_transform(Xtrain)

In [18]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train , Ytrain)

MultinomialNB()

In [20]:
X_test = cv.transform(Xtest)

In [21]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 4, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
MNB.score(X_test , Ytest)

0.9929762949956101

In [23]:
emails = ['hey i am looking for machine learning language on bengali tutorial' , 'My name is Ullash']

In [24]:
cv_mails = cv.transform(emails)

In [25]:
MNB.predict(cv_mails)

array([0, 0], dtype=int64)

# Performance Measure

In [26]:
pred = MNB.predict(X_test)

In [27]:
pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(Ytest , pred)

0.9929762949956101

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
confusion_matrix(Ytest , pred)

array([[862,   3],
       [  5, 269]], dtype=int64)

In [34]:
from sklearn.metrics import classification_report

In [36]:
print(classification_report(Ytest , pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       865
           1       0.99      0.98      0.99       274

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

